const box = document.getElementById("previewBox"),
  btr = document.getElementById("border-top-right"),
  btl = document.getElementById("border-top-left"),
  bbr = document.getElementById("border-bottom-right"),
  bbl = document.getElementById("border-bottom-left"),
  widthRange = document.getElementById("borderWidth"),
  borderColorPicker = document.getElementById("border-color"),
  borderBtns = document.querySelectorAll(".borderBtn"),
  borderAllBtn = document.querySelector(".borderAllBtn"),
  shadowBtns = document.querySelectorAll("#shadowBtn"),
  removeShadowBtn = document.getElementById("removeShadowBtn"),
  shadowBlurRange = document.getElementById("shadowBlur"),
  shadowSpreadRange = document.getElementById("shadowSpread"),
  backgroundBtn = document.querySelector("#custom-bg"),
  removeBackgroundBtn = document.getElementById("removeBackground"),
  backBackgroundBtn = document.querySelector(".back-arrow"),
  backgroundSlider = document.querySelector(".background-slider"),
  backgroundContainer = document.querySelector(".background-changer"),
  backgroundType = document.getElementById("background-type");

let palettesColors,
  solidColorPicker,
  gradientColor1Picker,
  gradientColor2Picker,
  firstColorGradient,
  secondColorGradient,
  directionRange,
  backgroundUrlInput,
  backgroundImageSize,
  backgroundImagePosition,
  backgroundImageRepeat;
